#Semantic Accuracy - Identify Ontology Contstraints
#The ontology sals the schema:recipeIngredient is schema:Recipe


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?s ?ingredient
WHERE {
  ?s <https://schema.org/recipeIngredient> ?ingredient .
  FILTER NOT EXISTS {
    ?s rdf:type <https://schema.org/Recipe> .
  }
}
ORDER BY ?s