PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?recipe ?time
WHERE {
  ?recipe a schema:Recipe .
  { ?recipe schema:cookTime ?time }
  UNION
  { ?recipe schema:prepTime ?time }

  FILTER ( DATATYPE(?time) != xsd:duration )
}

# Syntactic validity
# Invalid duration data type
# Quality dimension: Syntactic validity
# This query shows recipes that have cookTime or prepTime values that are not typed as xsd:duration. These wrongly typed values violate the expected datatype and could be because of, for instance, incorrectly parsed time information (eg. "nan").